---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: tools
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.5.6
    helm:
      values: |
        serviceAccount:
          name: "external-dns"
          annotations:
            "eks.amazonaws.com/role-arn": "arn:aws:iam::054000737513:role/k8s-main/ExternalDns"
        policy: "upsert-only"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
