apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: tools
  source:
    repoURL: 'git@github.com:Canida-Software/k8s-on-aws.git'
    path: applications/tools/external-secrets
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
