---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: tools
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.5.7
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
