apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://github.com/argoproj-labs/argocd-image-updater/manifests/base
- ghcr-pull-external-secret.yaml

patchesStrategicMerge:
- argocd-image-updater-config.patch.yaml
